---
title: "Non-Gaussian likelihood modeling in the lgpr package"
author: "Juho Timonen"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: true
#  pdf_document:
#    toc: true     
vignette: >
  %\VignetteIndexEntry{Non-Gaussian likelihood modeling in the lgpr package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#"
)
```

This vignette demonstrates how to fit a model with a non-Gaussian likelihood using the `lgpr` package.

```{r load}
library("lgpr")
```


## Generating negative binomial count data

```{r simulate, fig.width=7, fig.height=4.5}
# generate negative binomial data -----------------------------------------
set.seed(123)
simData <- simulate_data(N            = 10,
                         t_data       = seq(12, 72, by = 12),
                         covariates   = c(    1,1,2,2),
                         lengthscales = c(12,24,1,1,12,12),
                         relevances   = c(1,1,1,1,0,0),
                         noise_type   = "NB",
                         phi          = 2,
                         C_hat        = 1,
                         f_var        = 2,
                         t_jitter     = 1)


plot_simdata(simData, componentwise = F)
plot_simdata(simData, componentwise = T)
print(simData$data$y)
```


## Gaussian likelihood model
```{r gauss, fig.width=7, fig.height=6}
f1 <- lgp(formula  = y ~ id + age + x1 + x2 + z1 + z2, 
          data     = simData$data,
          iter     = 1000, 
          chains   = 1)
plot_posterior_f(f1)
```

## Negative Binomial likelihood model
```{r nb, fig.width=7, fig.height=6}
f2 <- lgp(formula    = y ~ id + age +  x1 + x2 +  z1 + z2,
          data       = simData$data,
          likelihood = "NB",
          iter       = 1000, 
          chains     = 1)
plot_posterior_f(f2) + ggplot2::ggtitle("Samples of g")
```
